spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
  main:
    allow-circular-references: true