spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quality_education
    username: postgres
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


telegram:
  token: 5230682813:AAEAnMB0ksKnPytRFeiONV7FOjW4rE1vT-E
  username: b15_Sarvar_bot